FROM golang AS build-env
RUN CGO_ENABLED=0 go get github.com/okzk/env-injector
 
FROM alpine:3.6
RUN apk --no-cache update &&\
    apk add --no-cache python3 &&\
    apk add --no-cache ca-certificates&&\
    python3 -m ensurepip &&\
    rm -r /usr/lib/python*/ensurepip &&\
    pip3 install --upgrade pip setuptools &&\
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi &&\
    rm -r /root/.cache &&\
    rm -rf /var/cache/apk/* &&\
    mkdir -p /src/rtmbot/plugins &&\
    cd /src/rtmbot&&\
    pip3 install rtmbot
 
COPY --from=build-env /go/bin/env-injector /usr/local/bin/
ENTRYPOINT ["env-injector"]
 
COPY ./requirements.txt /src/rtmbot/
COPY ./token_setting.py /src/rtmbot/
COPY ./temp.conf /src/rtmbot/
 
RUN pip install --no-cache-dir -r /src/rtmbot/requirements.txt
ARG SLACK_TOKEN
 
CMD cd /src/rtmbot &&\
    PYTHONPATH=. python3 token_setting.py $SLACK_TOKEN &&\
    PYTHONPATH=. python3 -u /usr/lib/python3.6/site-packages/rtmbot/bin/run_rtmbot.py
